---
title: "Przestrzenne zróżnicowanie drugiego piętra w drzewostanach sosnowych"
author: "Wojciech Kędziora"
date: "22-10-2017"
output:
  html_document:
    df_print: paged
  word_document:
    reference_docx: word-styles-reference-01.docx
---

```{r setup, include = FALSE}

library(MASS)
library(raster)
library(forcats)
library(stringr)
library(rgdal)
library(ggtern)
library(tmap)
library(tmaptools)
library(sf)
library(ks)
library(tidyverse) # should be loaded as last to make sure that its function work without any additional commands
# vignette("tmap-nutshell")

data(Europe, rivers) # loading data of Europe to plot it later as a background
vistula <- subset(rivers, name == "Vistula") # Vistula river to plot is as a reference
rm(rivers)
poland <- read_shape("POL_adm_shp/POL_adm0.shp", as.sf = TRUE) # Poland administrative boundary

# function that filters species and add GPS position to a sample plot
add_gps <- function(dataset, col_name = "gat") {
  dataset %>% 
    left_join(., gps_coord, by = "nr_punktu") -> y
  y <- st_as_sf(y, coords = c("lon", "lat"), crs = 4326)
  return(y)
}

# function for fast map drawing
draw_map <- function(dataframe, facet = FALSE) {
  map <- tm_shape(Europe, bbox = "Poland", projection="longlat", is.master = TRUE) + tm_borders() + # Polska or Europe for performance
    tm_shape(vistula) + tm_lines(col = "steelblue", lwd = 4) +
    qtm(dataframe, dots.alpha = 0.5) 
  if (facet == TRUE) 
    map + tm_facets("gat", free.coords = TRUE, drop.units = TRUE) 
  else 
    map
}

draw_maps_4 <- function(dataframe, x, facet = FALSE){
  dataframe %>% filter(gat == x) -> subset
  map <- tm_shape(Europe, bbox = "Poland", projection="longlat", is.master = TRUE) + tm_borders() +
    tm_shape(vistula) + tm_lines(col = "steelblue", lwd = 3) +
    qtm(subset, dots.alpha = 0.5) + 
    tm_layout(asp = 0, outer.margins=0)
  if (facet == TRUE) 
    map + tm_facets(by = "group", free.coords = TRUE, drop.units = TRUE, drop.empty.facets = FALSE)
  else 
    map
}

density <- function(x) {
  min_x <- c(13.8)
  max_x <- c(24.5)
  min_y <- c(49.0)
  max_y <- c(55.0)
  coords <- as.data.frame(st_coordinates(x$geometry))
  density_x <- kde2d(coords$X, coords$Y, n = 500, h = 1, lims = c(min_x, max_x, min_y, max_y)) 
  r = raster(density_x)
  return(r)
}

draw_density_plot <- function(dataframe, x) {
  dataframe %>% filter(gat == x) -> subset
r <- density(subset)
rr <- mask(r, as(poland, "Spatial"))
map <- tm_shape(rr) + tm_raster("layer", breaks = seq(0, 0.1, by=0.02),  legend.show = TRUE) +
  tm_shape(poland) + tm_borders() +
  tm_shape(vistula) + tm_lines(col = "steelblue", lwd = 3) +
  tm_shape(subset) + tm_dots(alpha = 0.1) +
  tm_layout(asp = 0, outer.margins=0, legend.position = c("LEFT", "BOTTOM"))
map
}

wykres <- . %>% 
  factor() %>% 
  fct_lump(n = 10) %>%
  fct_infreq() %>%
  fct_relevel("Other", after = Inf) %>%
  fct_count() 
  # ggplot(., aes(f, n)) +
  # geom_bar(stat = "identity")
  
knitr::opts_chunk$set(echo = FALSE)
```

```{r loading_data, message = FALSE}
trees_05_raw <- read_tsv("trees_05_raw.txt") # trees shorter than 0.5 m
trees_05_3_raw <- read_tsv("trees_05_3_raw.txt") # trees teller than 0.5 m and smaller than 3 cm dbh
trees_3_7_raw <- read_tsv("trees_3_7_raw.txt") # trees between 3 and 7 cm dbh
trees_7_raw <- read_tsv("trees_7_raw.txt") # trees above 7 cm dbh
plot_raw <- read_tsv("plot_raw.txt") # sample plot data
gps_coord_raw <- read_tsv("gps_coord_raw.txt") # GPS coordinates
sites_raw <- read_tsv("sites_raw.txt") # site description
```

```{r preparation, warning = FALSE}
# I am querying for area of sample plot needed later
plot_raw %>% # raw data loading to pipe
  as_tibble(.) %>% # changing format to tibble
  filter(NR_CYKLU == 2) -> plot # filtering out only second cycle & creating a new tibble

# I need doubles for later use of Spatial Data 
gps_coord_raw %>%
  as_tibble(.) %>%
  type_convert(.) %>%
  dplyr::select(nr_punktu = NR_PUNKTU,
         lon = DLUGOSC,
         lat = SZEROKOSC) -> gps_coord

# I am loading site description data
sites_raw %>%
  as_tibble(.) %>%
  rename_all(tolower) %>% # changing all columns to lower case
  dplyr::select(nr_punktu, nr_cyklu, nr_podpow, rok_w_cyklu, rdlp, nadl, kraina, gat_pan_pr, wiek_pan_pr, 
         b_pion_pow_pr, tsl, okr_tsl, stan_siedl) %>%
  dplyr::filter(nr_cyklu == 2, gat_pan_pr == "SO") %>%
  dplyr::select(-nr_cyklu) %>%
  type_convert(., col_types = cols_only(gat_pan_pr = col_factor(levels = NULL))) -> sites # converting column to factor

# lowest trees (h < 0.5 m) data loading and wrangling ----------------------------------------------------------------

trees_05_col <- c("gat", "pokr", "war", "uszk_rodz1", "uszk_proc1")
trees_05_raw %>% # raw data loading to pipe
  as_tibble(.) %>% # changing format to tibble
  filter(NR_CYKLU == 2) %>% # filtering out only second cycle
  rename_all(tolower) %>%
  filter(war == 1) %>% # we want only trees
  dplyr::select(-c(nr_cyklu, lp, id, uszk_rodz2, uszk_proc2)) %>%
  mutate_at(trees_05_col, funs(factor(.))) %>%
  mutate(gat = fct_collapse(gat, 
                            DB = c("DB", "DB.S", "DB.B"),
                            BRZ = c("BRZ", "BRZ.O"))) -> trees_05 # creating a new tibble

trees_05$pokr <- factor(trees_05$pokr, ordered = TRUE, levels = c("+", "1", "5", "10", "15", "20", "25", "30", "35", "40", "45",
                                                                "50", "55", "60", "65", "70", "75", "80", "85", "90", 
                                                                "95", "100"))

trees_05_gps <- add_gps(trees_05)

# medium trees (h > 0.5 m & dbh < 3 cm) data loading and wrangling -----------------------------------------------------

trees_05_3_col <- c("gat", "war", "uszk_rodz1", "uszk_proc1")
trees_05_3_raw %>% # raw data loading to pipe
  as_tibble(.) %>% # changing format to tibble
  filter(NR_CYKLU == 2) %>% # filtering out only second cycle
  rename_all(tolower) %>%
  filter(war == 1) %>%
  dplyr::select(-c(nr_cyklu, lp, id, uszk_rodz2, uszk_proc2)) %>%
  mutate_at(trees_05_3_col, funs(factor(.))) %>%
  mutate(gat = fct_collapse(gat, 
                            DB = c("DB", "DB.S", "DB.B"),
                            BRZ = c("BRZ", "BRZ.O"))) -> trees_05_3 # creating a new tibble

trees_05_3_gps <- add_gps(trees_05_3)

# high trees (3 cm < dbh < 7 cm) data loading and wrangling ---------------------------------------------------------
trees_3_7_col <- c("gat", "war", "uszk_rodz1", "uszk_proc1")
trees_3_7_raw %>% # raw data loading to pipe
  as_tibble(.) %>% # changing format to tibble
  filter(NR_CYKLU == 2) %>% # filtering out only second cycle
  rename_all(tolower) %>%
  filter(war == 1) %>%
  dplyr::select(-c(nr_cyklu, lp, id, uszk_rodz2, uszk_proc2)) %>%
  mutate_at(trees_3_7_col, funs(factor(.))) %>%
  mutate(gat = fct_collapse(gat, 
                            DB = c("DB", "DB.S", "DB.B"),
                            BRZ = c("BRZ", "BRZ.O"))) -> trees_3_7 # creating a new tibble

trees_3_7_gps <- add_gps(trees_3_7)

# highest trees (dbh > 7 cm) data loading and wrangling -------------------------------------------------------------
trees_7_col <- c("gat", "war")
trees_7_raw %>% # raw data loading to pipe
  as_tibble(.) %>% # changing format to tibble
  filter(NR_CYKLU == 2) %>% # filtering out only second cycle
  rename_all(tolower) %>%
  filter(war == 2 | war == 3) %>%
  filter(odl >= 56 & odl <= 259) %>% # using the same dimensions as for other layers of sample plot
  dplyr::select(nr_punktu, nr_cyklu, nr_podpow, gat, wiek, war, azymut, odl, h, d13) %>%
  mutate_at(trees_7_col, funs(factor(.))) %>%
  type_convert(col_types = cols_only(nr_punktu = "i")) %>%
  mutate(gat = fct_collapse(gat, 
                            DB = c("DB", "DB.S", "DB.B"),
                            BRZ = c("BRZ", "BRZ.O"))) %>%
  filter(gat %in% c("AK", "BK", "BRZ", "CZR", "DB", "DB.C", "DG", "GB", "IWA", "JB", "JD", "JKL", "JRZ", "JS", 
                    "JW", "KL", "KL.P", "LP", "MD", "OL", "OL.S", "OS", "SO", "ŚW", "WB", "WZ", "WZ.P")) -> trees_7 # creating a new tibble

trees_7_gps <- add_gps(trees_7)

# grouping altogether all sample plot layers ------------------------------------------------------------------------
bind_rows("< 0.5m" = trees_05, 
          "> 0.5m & < 3cm" = trees_05_3, 
          "3cm < dbh < 7cm" =  trees_3_7, 
          "dbh > 7cm" = trees_7, 
          .id = "group") %>% 
  group_by(gat) %>% 
  filter(n() > 99) %>% 
  ungroup() -> trees_all

# I need to add age restriction to avoid young pine monocultures
sites %>% select(nr_punktu, nr_podpow, gat_pan_pr, wiek_pan_pr) %>% left_join(trees_all %>% select(-nr_punktu), by = "nr_podpow") -> sites_so

sites_so_gps <- add_gps(sites_so)
sites_so_gps$gat <- factor(sites_so_gps$gat)
sites_so_gps$group <- factor(sites_so_gps$group)
```

```{r plotting_prep}
# gatunki <- as.list(sort(as.character(unique(sites_so_gps$gat))))
# gatunki_sample <- as.list(gatunki[1:3])
gatunki <- c("BK", "JD", "ŚW", "GB")
names(gatunki) <- gatunki
```

## Buk
```{r BK}
BK <- read_shape("ranges/Fagus_sylvatica_EUFORGEN.shp", as.sf = TRUE)
draw_maps_4(sites_so_gps, gatunki[1], facet = TRUE)
draw_density_plot(sites_so_gps, gatunki[1]) + tm_shape(BK) + tm_fill(alpha = 1)
```

## Jodła
```{r JD}
JD <- read_shape("ranges/Abies_alba_EUFORGEN.shp", as.sf = TRUE)
draw_maps_4(sites_so_gps, gatunki[2], facet = TRUE)
draw_density_plot(sites_so_gps, gatunki[2])  + tm_shape(JD) + tm_borders(col = "blue", alpha = 0.5)
```

## Świerk
```{r ŚW}
SW <- read_shape("ranges/Picea_abies_EUFORGEN.shp", as.sf = TRUE)
draw_maps_4(sites_so_gps, gatunki[3], facet = TRUE)
draw_density_plot(sites_so_gps, gatunki[3])  + tm_shape(SW) + tm_borders(col = "blue", alpha = 0.5)
```

## Grab
```{r GB}
draw_maps_4(sites_so_gps, gatunki[4], facet = TRUE)
draw_density_plot(sites_so_gps, gatunki[4])
```
